### ISSUE TITLE
Check-In Process (customization)

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#19]
Check-in option can be found easier than before. And the deletion of the checkin actually deletes it instead of hiding it which was the previous functionality.

**Comment by safarsi** [comment]
COMPLETED:
checkin.js is modified to not use id "tap-to-check" anymore. "check-in" id is changed to "checkin" because the original name had some css associated with it which we didn't need. Got rid of function StartCheckIn() since the functionality wasn't needed anymore. 
dashboard.js --> added a force refresh in line 107 so the remove functionality of a visitor works.
visitors.html --> lines 177-209 is added for check-in functionality on visitors page.

**Comment by i3dly** [comment]
Redesign Work in Progress: The check-in modal that appears when clicking the 'check-in' text on the bottom left of the visitors page has been extracted from the 'main-content' div in html to its own div outside of that 'main-content' block (this is so that it would be better understood if/when the modal is a shared element across multiple pages, which would require adding the modal code to each dashboard page).

Bootstrap and Neon styles (bound to class) have been overwritten with higher priority styles (bound to ids), so that more granular control and search over modules' styles can be achieved. To search for non-default (bootstrap, neon, etc.) styles, search for 'override_[module's purpose]_[module's original name]. For example, the original bootstrap module, which is a class '.modal-dialog', has had its styles overwritten with an id 'override_checkin_modal-dialog'. You can find these new styles in the shared-dashboard.css file in client/assets/native/css, between the 'Begin' and 'End' 'Check-In Styles' comment blocks.

The modal has been redesigned with a more consistent style, with more consistent element sizing, better separation of element's functions (header, body and footer), and placeholder texts have been replaced with outside labels instead.

The check-in feature in the top right of the dashboard now triggers the check-in modal instead of redirecting to the checkin page (checkin.html), because the checkin page had broken css, such that form elements became hidden in the background, instead of shown in the foreground, and the bottom check-in button was featureless ('tap to check-in' button had no functionality, because the checkin feature was actually bound to a hidden submit input that was hidden as well in the background).

These check-in features were only applied to the visitors page for now, until more confirmation for this feature to be applied to other pages is given. In the other pages, clicking the 'check-in' button on the top-right gear will invoke the old behavior and redirect to the old checkin page (so client/assets/native/css/checkin.css and client/assets/native/views/checkin.html still exist in the project structure, but have been extracted out of visitors.html). If/when these changes are to be applied to the other pages, the html for the checkin modal will be copy+pasted from visitors to other dashboard pages (the modal will open locally to that page), and the script files related to the checkin functionality will have to be linked to those pages as well.

Otherwise, changed some indentation (whitespacing) of visitors.html, visitors.css and checkin.css.
