### ISSUE TITLE
Form-Builder needs to be saved and used.

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#32]

**Comment by ghost** [comment]
Forms Documentation:

Back-End:
router.get('/template/company/:id', controller.template.findByCompanyId);
- Gets all the forms for a specific company
- GET /api/form/template/company/<company_id>
router.get('/template/:template_id', controller.template.findByTemplateId);
- Gets a particular form's template
- Used for generating forms to be filled out by customers on the front end
- GET /api/form/template/<template_id>
router.delete('/template/:template_id', controller.template.delete);
- delete's a form template
- DELETE /api/form/template/<template_id>
router.post('/template', controller.template.create);
- Creates a form template from request body
- POST /api/form/template
Body: {
"company_id" : "<company_id>",
"name": "<form_name>",
"format": [
{
"type": "text",
"subtype": "tel",
"required": true,
"label": "Phone Number",
"name": "text-1496706929086"
},
{
"type": "text",
"subtype": "email",
"required": true,
"label": "Email",
"name": "text-1496706930024"
},
{
"type": "text",
"label": "Text Field",
"name": "text-1496706931586",
"subtype": "text"
},
{
"type": "date",
"label": "Date Field",
"name": "date-1496707034748"
},
{
"type": "number",
"label": "Number",
"name": "number-1496707035941"
}
]
}
- The four supported entry fields right now are Phone, Email, Text, Date, and Number and those are represented respectively above in the format array of the request body
- All other types will be regected

router.post('/store', controller.forms.create);
- Saves a submitted form by a visitor
- POST /api/form/save
Body: {
"text-1497247266544":
{
"title": "Text Field",
"required": "false",
"format": "phone",
"type": "string",
"value": "1234567890"
},
"text-1497247267744":
{
"title": "Text Field",
"required": "false",
"format": "email",
"type": "string",
"value": "aa@aa.aa"
},
"text-1497247268053":
{
"title": "Text Field",
"required": "false",
"type": "string",
"value": "aa aa"
},
"number-1497247269450":
{
"title": "Number",
"required": "false",
"type": "number",
"value": "11"
},
"date-1497247270148":
{
"title": "Date Field",
"required": "false",
"format": "date",
"type": "string",
"value": "11/11/1111"
}
}

Front-End:

Forms button on the sidebar will check if the company has any forms. If any forms exist, it will generate the forms page which will displays all the forms there. If no forms exist it will take you to the form builder where you can begin to generate your first form.

The Form Builder has a lot of capabilities, but our backend only supports Text, Email, Phone (which are subtypes of the text field) and Number and Date. Adding any other types to your form will throw a 400 on the backend

The Form viewer will show you a list of forms, the ability to delete or add new ones, and the ability to open up the forms, fill them out, and store them

Needs to Be Done:

Disable Form-Builder functionality until those options are added
Design a schema so that forms can be connected to visitors
Create a Page to view all the forms submitted per company

**Comment by endeavors** [comment]
done
