### ISSUE TITLE
Fix the time entry.

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#60]

**Comment by i3dly** [comment]
COMPLETE: Fixed on branch DevBugFix

Changed appointments' page 'Date' and 'Time' inputs from text types to date and time types.
Vanilla HTML appears to subtract 1 day from the datepicker as well, so added 1 day on formatDate in appointments.js to adjust accordingly (so that the customer-selected date is what gets saved, rather than that date minus 1 day).

Additionally fixed redirecting between forms and appointments (when selecting from one to the other from the left-hand side navbar). Before, selecting appointments from forms would do nothing, and selecting forms from appointment-history would not use the formhelper, but immediately redirect to form-builder, even if a form has already been saved (expected to navigate to forms instead of form-builder in this case).
