### ISSUE TITLE
Email (sending reminder emails)

### ISSUE THREAD

**Issue by safarsi** [CSE112Spring17/emissary#8]

**Comment by i3dly** [comment]
COMPLETE: This feature has been merged onto Dev (as of the meeting on June 3rd, 2017).
Upon creating a successful appointment on appointments.html, client/assets/native/js/appointments.js sends an ajax call from updateApptList that invokes the create function in server/routes/appointment/appointment.controller.js. In this create function, I added a method call to Email.notifyAppointment (which exists in server/notification/email.js), that constructs a message body from the passed parameters, and sends an email.

**Comment by i3dly** [comment]
New functions:
exports.notifyAppointment = function(fname, lname, company_id, date, email);
(In server/notification/email.js)

Takes as paramaters, string values (originally as JSON values) fname, lname, company_id, date and email. Returns 'error' and logs the error to the console when mail is unsuccessfully sent. Otherwise, returns 'Message sent' and logs the messageId and response  to the console when mail is successfully sent.
